blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('search/', views.search, name='search'),
    path('python/', views.PythonView.as_view(), name='python'),
    path('c/', views.CView.as_view(), name='c'),
    path('linux/', views.LinuxView.as_view(), name='linux'),
    path('algorithm/', views.AlgorithmView.as_view(), name='algorithm'),
    path('db/', views.DbView.as_view(), name='db'),
    path('someelse/', views.SomeelseView.as_view(), name='someelse'),
]

templates/base.html
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html>
<head>
    <title>欢迎来到随意的博客</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link href="https://cdn.bootcdn.net/ajax/libs/highlight.js/10.4.1/styles/atelier-heath-light.min.css" rel="stylesheet">
    <style type="text/css">
        .bgimg{
            background-attachment: fixed;
            background-repeat: no-repeat;
            background-size: 100% 100%;
            background-image: url("{% static 'blog/img/bg.png' %}");
            opacity: 0.75;
        }
    </style>
    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/10.4.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script src="//cdn.bootcss.com/highlightjs-line-numbers.js/1.1.0/highlightjs-line-numbers.min.js"></script>
    <script>hljs.initLineNumbersOnLoad();</script>
</head>

<body class="bgimg">
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{%url 'blog:index' %}"><b>随意 的</b> 博客</a></h1>
                </div>
            <div>
            </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <!--<li class="cl-effect-11"><a href="{%url 'blog:index' %}" data-hover="首页">首页</a></li>-->
                            <li class="cl-effect-11"><a href="{%url 'blog:python'%}" data-hover="python">python</a></li>
                            <li class="cl-effect-11"><a href="{%url 'blog:c'%}" data-hover="c++">c++</a></li>
                            <li class="cl-effect-11"><a href="{%url 'blog:linux'%}" data-hover="linux">linux</a></li>
                            <li class="cl-effect-11"><a href="{%url 'blog:algorithm'%}" data-hover="算法">算法</a></li>
                            <li class="cl-effect-11"><a href="{%url 'blog:db'%}" data-hover="数据库">数据库</a></li>
                            <li class="cl-effect-11"><a href="{%url 'blog:someelse'%}" data-hover="其他">其他</a></li>
                            <li class="cl-effect-11"><a href="https://github.com/moranhh/" data-hover="github">github</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
            <div class="col-md-12 col-sm-5 col-xs-8">
                <i><h5><br><font color='#ebd143')>最难过时光 就要一起开口笑 啦啦啦啦~啦啦~啦啦啦~~ happy keep on everyday</font></h5></i>
            </div>
        </div>
    </header>
    {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ message }}
      </div>
    {% endfor %}
{% endif %}
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4 ">
                <!--目录-->
                {% block toc %}
                {% endblock toc %}

                <!--最近文章-->
                {% show_recent_posts %}

                <!--日期归档-->
                {% show_archives %}

                <!--分类-->
                {% show_categories %}

                <!--标签-->
                {% show_tags %}
                
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>    
        </div>
    </div>
</div>
<!--<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>-->

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">github</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>